package com.aiwebauditor.model;

public enum ValidationStatus {
  AUTOMATICALLY_VALIDATED,
  PARTIALLY_VALIDATED,
  NOT_TESTED,
  BLOCKED_AUTHENTICATION,
  BLOCKED_CAPTCHA_OR_MFA,
  SKIPPED_FOR_SAFETY,
  FAILED,
  MANUAL_REVIEW_REQUIRED
}
